### ISSUE TITLE
Failure if `idSelector` value is integer

### ISSUE THREAD

**Issue by denisnazarov** [mediachain/aleph#50]
```
$ mcclient publish --idSelector id museum.tate.artworks TwoWorks.ndjson
Error publishing statements:  { Error: Bad Request
Error: json: cannot unmarshal number into Go value of type string

    at RestError (/Users/denisnazarov/web/rc/aleph/lib/client/api/RestClient.js:31:5)
    at response.text.then.responseBody (/Users/denisnazarov/web/rc/aleph/lib/client/api/RestClient.js:53:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  statusCode: 400,
  response:
   Body {
     url: 'http://localhost:9002/publish/museum.tate.artworks',
     status: 400,
     statusText: 'Bad Request',
     headers: Headers { _headers: [Object] },
     ok: false,
     body:
      PassThrough {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     bodyUsed: true,
     size: 0,
     timeout: 0,
     _raw: [ <Buffer 45 72 72 6f 72 3a 20 6a 73 6f 6e 3a 20 63 61 6e 6e 6f 74 20 75 6e 6d 61 72 73 68 61 6c 20 6e 75 6d 62 65 72 20 69 6e 74 6f 20 47 6f 20 76 61 6c 75 65 ... > ],
     _abort: false,
     _bytes: 66 } }
All statements published successfully
```

- Fails if id is not a string 
- Gives vague error message
- Still says "All statements published successfully" even though it failed

Related to https://github.com/mediachain/concat/issues/70

**Comment by vyzo** [comment]
This most likely comes from the json decoder for simple statement bodies, which expects a list of strings for the wki references.
That's also how we have specified the references in the rfc, so it's not a bug in concat.

Nonetheless, the client certainly shouldn't claim that statements were published successfully when there is a failure like this.

**Comment by yusefnapora** [comment]
I'll add a `.toString` on the id and make sure we correctly catch the errors
